spring:
  datasource:
#    url: jdbc:sqlserver://localhost:1433;databaseName=finshark;encrypt=false
    url: jdbc:sqlserver://localhost:1433;databaseName=WebApi;encrypt=false
    username: tester
    password: tester
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092 # Kafka broker address
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
camunda.bpm:
  admin-user:
    id: demo
    password: demo
  client:
    base-url: http://localhost:8080/engine-rest # The URL pointing to the Camunda Platform Runtime REST API
    async-response-timeout: 1000 # Defines the maximum duration of the long-polling request
    worker-id: spring-boot-client # Identifies the worker towards the Engine
#      basic-auth: # Configure if REST API is secured with basic authentication
#        username: my-username
#        password: my-password
    subscriptions:
      creditScoreChecker:
        process-definition-key: loan_process
        lock-duration: 300000 # Lock for 5 minutes (enough time for Kafka processing)
      loanGranter:
        lock-duration: 10000 # Defines for how long the External Tasks are locked until they can be fetched again

logging.level.org.camunda.bpm.client: info